### ISSUE TITLE
Full URLs not fetched

### ISSUE THREAD

**Issue by bradsoo** [stefanjudis/contentful-link-checker-ui-extension#1]
Steps to reproduce:
1. Within the Contentful web app, have a blog post with content and multiple links.
2. Have at least the following Medium link (e.g. https://medium.com/@luisvieira_gmr/understanding-the-critical-rendering-path-rendering-pages-in-1-second-735c6e45b47a)
3. See "URL Validation" section, and observe only part of the URL is parsed and it registers as a 404 link (e.g. https://medium.com/@luisvieira_gmr/understanding)

**Comment by stefanjudis** [comment]
I think I fixed it and will update tomorrow. :) Feel free to reopen when it's not fixed.
