### ISSUE TITLE
Not checking for translated fields

### ISSUE THREAD

**Issue by atilafassina** [stefanjudis/contentful-link-checker-ui-extension#2]
First of all, huge thanks for this project!! ❤️

---

We may have found an issue, though: the extension only checks for the main language of each field, so when you add translations for links (e.g.: localised slugs) and editor isn't careful, it may suggest a false positive, considering the list of URLs is hidden by default

<details><summary>screenshot</summary>

![ui-checker-translated-fields](https://user-images.githubusercontent.com/2382552/42557479-fc880e32-84ee-11e8-8b42-5ffc2bebf9ad.png)

</details>

### possible fix:
After matching that the main language is a URL, we could use `fields[key]._fieldLocales` array to check each translation.

--- 

Please, let me know what you think and I'll gladly attempt a PR to implement it 😎

**Comment by stefanjudis** [comment]
Ja I missed the multi language part. :D That's a great idea – go for it. 😊

**Comment by stefanjudis** [comment]
Should be fixed now. :)
